name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Automated Ping
        run: curl -s -o /dev/null -w "%{http_code}" https://spatiotemporal-engine.streamlit.app/
